
services:
  gunicorn1:
    image: gunicorn-app
    deploy: 
      replicas: 2  
    expose:
      - "8000"
    restart: always
    networks:
      - weather-network

  gunicorn2:
    image: gunicorn-app 
    expose:
      - "8000"
    restart: always
    networks:
      - weather-network

  nginx:
    image: nginx-image  
    ports:
      - "80:80"
    depends_on:
      - gunicorn1
      - gunicorn2
    restart: always
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
